import { MicoEvent } from "@/types/event";

export const mockEvents: MicoEvent[] = [
  {
    id: "evt-001",
    title: "Hack Michigan (HackMI) 2026",
    description:
      "Produced by Compass Detroit in partnership with GDG Detroit and IBM, Hack Michigan challenges participants to use AI and open-source technologies to build proof-of-concept solutions that modernize Michigan industries — manufacturing, mobility, agriculture, small business, sustainability, education, and urban planning. A multi-day hackathon at TechTown Detroit.",
    location: "TechTown Detroit, 440 Burroughs St, Detroit, MI 48202",
    locationType: "detroit-metro",
    eventType: "hackathon",
    eventDate: "2026-05-15T09:00:00-04:00",
    aiSummary: {
      whyAttend: "Build AI-powered solutions for Michigan industries in a 3-day hackathon produced by Compass Detroit.",
      whosThere: "Developers, designers, and data scientists from across Michigan. Sponsors include IBM and Google.",
      vibe: "High-energy collaborative hacking with meals, mentors, and prizes. Access code: HACKMI.",
    },
    source: "ibm_rpa",
    matchScore: 96,
    rsvpCount: 150,
    createdAt: "2026-04-20T12:00:00Z",
  },
  {
    id: "evt-002",
    title: "Michigan Tech Week 2026 — Future State",
    description:
      "Michigan's premier convening for tech and high-growth entrepreneurship, presented by the Michigan Founders Fund. Three days of programming at Michigan Central featuring corporate matchmaking with 50+ global corporations, the Venture Together Competition ($100K grand prize), immersive workshops, panels, and networking.",
    location: "Michigan Central, 2001 15th St, Detroit, MI 48216",
    locationType: "detroit-metro",
    eventType: "networking",
    eventDate: "2026-05-19T09:00:00-04:00",
    aiSummary: {
      whyAttend: "Michigan's biggest startup and tech conference — 500+ corporate matchmaking meetings and a $100K pitch competition.",
      whosThere: "Founders, investors, corporate innovation leaders, and the broader Michigan startup ecosystem.",
      vibe: "Professional but energizing. Held at the newly renovated Michigan Central, Ford's iconic train station.",
    },
    source: "api",
    matchScore: 88,
    rsvpCount: 800,
    createdAt: "2026-04-01T10:00:00Z",
  },
  {
    id: "evt-003",
    title: "IWD Innovation Summit 2026 — Break the Pattern",
    description:
      "Organized by Compass Detroit in partnership with GDG Detroit and Google Women Techmakers, the International Women's Day Innovation Summit focused on empowering women in tech. Features keynotes, hands-on workshops, career panels, and community sessions across tracks like 'Level Up,' 'Build with AI,' 'AI Foundations,' and 'Leadership.'",
    location: "Little Caesars Global Resource Center, Downtown Detroit, MI",
    locationType: "detroit-metro",
    eventType: "panel",
    eventDate: "2026-03-28T09:00:00-04:00",
    aiSummary: {
      whyAttend: "Full-day summit exploring how to disrupt traditional pathways and challenge systemic barriers in tech, guided by the 'Break the Pattern' theme.",
      whosThere: "Women technologists, creators, leaders, and allies from across Michigan's tech ecosystem. Organized by Compass Detroit & Women Techmakers.",
      vibe: "Empowering and community-driven. Multiple hands-on tracks from AI foundations to leadership development.",
    },
    source: "ibm_rpa",
    matchScore: 82,
    rsvpCount: 200,
    createdAt: "2026-02-15T09:00:00Z",
  },
  {
    id: "evt-004",
    title: "Detroit Pride Innovation Summit — Break the Pattern in Tech",
    description:
      "Hosted in partnership with Compass Detroit and GDG Detroit, this summit spotlights how LGBTQ+ voices are transforming technology — particularly in AI and emerging fields — through leadership, bold thinking, and creativity. Features panel discussions, technical sessions, workshops, and networking.",
    location: "TechTown Detroit, 440 Burroughs St, Detroit, MI 48202",
    locationType: "detroit-metro",
    eventType: "panel",
    eventDate: "2026-06-14T10:00:00-04:00",
    aiSummary: {
      whyAttend: "Amplifying LGBTQ+ technologists and fostering inclusive innovation in Michigan's tech ecosystem.",
      whosThere: "LGBTQ+ tech professionals, allies, and community leaders. Co-organized by Compass Detroit and GDG Detroit.",
      vibe: "Inclusive, inspiring, and action-oriented. Focused on career advancement and inclusive leadership in AI.",
    },
    source: "ibm_rpa",
    matchScore: 78,
    rsvpCount: 120,
    createdAt: "2026-05-01T10:00:00Z",
  },
  {
    id: "evt-005",
    title: "D-NewTech Detroit — Monthly Startup Meetup",
    description:
      "D-NewTech (DNT) is Detroit's longest-running monthly tech meetup, hosted at TechTown Detroit on the 2nd Wednesday of each month. Features 7-minute pitch presentations from startups, guest speakers, community announcements, and dedicated networking time with drinks.",
    location: "TechTown Detroit, 440 Burroughs St, Detroit, MI 48202",
    locationType: "detroit-metro",
    eventType: "networking",
    eventDate: "2026-06-10T18:30:00-04:00",
    aiSummary: {
      whyAttend: "Detroit's longest-running monthly tech meetup — hear startup pitches and network with the local ecosystem.",
      whosThere: "Startup founders, developers, investors, and tech enthusiasts from Metro Detroit.",
      vibe: "Casual and welcoming. Networking from 6:30 PM, pitches at 7:00 PM. Drinks included.",
    },
    source: "api",
    matchScore: 85,
    rsvpCount: 60,
    createdAt: "2026-05-15T14:00:00Z",
  },
  {
    id: "evt-006",
    title: "Michigan DevFest 2026",
    description:
      "The 12th annual Michigan DevFest, organized by GDG Detroit, GDG Ann Arbor, GDG Toledo, GDG UofM Dearborn, GDG Windsor, and Compass Detroit. Expect an Agentic AI Hackathon, technical sessions, and workshops covering AI/ML, cloud platforms, web development, and leadership. Previously held at Wayne State and MotorCity Casino Hotel.",
    location: "Detroit, MI (Venue TBA)",
    locationType: "detroit-metro",
    eventType: "workshop",
    eventDate: "2026-11-20T09:00:00-05:00",
    aiSummary: {
      whyAttend: "Michigan's premier developer conference — AI hackathon, technical sessions, and workshops across multiple tracks.",
      whosThere: "Developers from 5+ GDG chapters across Michigan, Ohio, and Ontario. Organized with Compass Detroit.",
      vibe: "Two-day format: Day 1 hackathon, Day 2 conference sessions. Community-driven and highly technical.",
    },
    source: "ibm_rpa",
    matchScore: 93,
    rsvpCount: 300,
    createdAt: "2026-05-10T08:00:00Z",
  },
];
