import { MicoEvent } from "@/types/event";

export const mockEvents: MicoEvent[] = [
  {
    id: "evt-001",
    title: "Detroit AI Innovators Meetup",
    description:
      "Join Detroit's top AI engineers for an evening of talks, demos, and networking focused on RAG architectures and autonomous agents.",
    location: "TechTown Detroit, 440 Burroughs St, Detroit, MI",
    locationType: "detroit-metro",
    eventType: "networking",
    industry: "Technology",
    eventDate: "2026-05-24T18:00:00-04:00",
    aiSummary: {
      whyAttend: "Deep dive into RAG architectures and agentic AI workflows.",
      whosThere: "Engineers from GM, Ford, and local AI startups.",
      vibe: "Casual networking with pizza and craft beer from Atwater Brewery.",
    },
    source: "ibm_rpa",
    matchScore: 95,
    rsvpCount: 48,
    createdAt: "2026-05-10T12:00:00Z",
  },
  {
    id: "evt-002",
    title: "Michigan Nursing Career Fair",
    description:
      "Connect with top Michigan health systems including Beaumont, Henry Ford Health, and Corewell Health. On-site interviews, resume reviews, and sign-on bonus info sessions.",
    location: "TCF Center, 1 Washington Blvd, Detroit, MI",
    locationType: "detroit-metro",
    eventType: "career-fair",
    industry: "Healthcare",
    eventDate: "2026-06-01T09:00:00-04:00",
    aiSummary: {
      whyAttend: "Direct access to hiring managers from Michigan's largest health systems. Many roles offering sign-on bonuses.",
      whosThere: "Recruiters from Beaumont, Henry Ford Health, Corewell Health, and Michigan Medicine.",
      vibe: "Professional but welcoming. Wear scrubs or business casual. Free lunch provided.",
    },
    source: "ibm_rpa",
    matchScore: 88,
    rsvpCount: 320,
    createdAt: "2026-05-12T09:00:00Z",
  },
  {
    id: "evt-003",
    title: "Grand Rapids Manufacturing Innovation Summit",
    description:
      "Explore advanced manufacturing techniques, CNC automation, and supply chain optimization. Featuring demos from Steelcase, Haworth, and Gentex.",
    location: "DeVos Place, 303 Monroe Ave NW, Grand Rapids, MI",
    locationType: "grand-rapids",
    eventType: "conference",
    industry: "Manufacturing",
    eventDate: "2026-06-13T08:00:00-04:00",
    aiSummary: {
      whyAttend: "Hands-on demos of Industry 4.0 tech from West Michigan's manufacturing leaders.",
      whosThere: "Production managers, CNC operators, and supply chain pros from Steelcase, Haworth, and Gentex.",
      vibe: "High-energy conference with live machinery demos. Safety glasses provided.",
    },
    source: "api",
    matchScore: 76,
    rsvpCount: 180,
    createdAt: "2026-05-08T15:00:00Z",
  },
  {
    id: "evt-004",
    title: "Women in Michigan Leadership Panel",
    description:
      "Hear from women leaders across Michigan's diverse industries about career paths, mentorship, and building inclusive workplaces.",
    location: "Virtual (Zoom)",
    locationType: "virtual",
    eventType: "community",
    industry: "Cross-Industry",
    eventDate: "2026-06-05T12:00:00-04:00",
    aiSummary: {
      whyAttend: "Inspiring stories from women shaping Michigan's economy across tech, healthcare, and manufacturing.",
      whosThere: "Leaders from Duo Security, Beaumont Health, Steelcase, and Michigan State University.",
      vibe: "Professional and empowering. Q&A with audience participation.",
    },
    source: "ibm_rpa",
    matchScore: 82,
    rsvpCount: 95,
    createdAt: "2026-05-14T10:00:00Z",
  },
  {
    id: "evt-005",
    title: "Ann Arbor Educators Professional Development Workshop",
    description:
      "A hands-on workshop for K-12 educators covering project-based learning, SEL integration, and AI-assisted lesson planning tools.",
    location: "University of Michigan School of Education, Ann Arbor, MI",
    locationType: "ann-arbor",
    eventType: "training",
    industry: "Education",
    eventDate: "2026-06-20T09:00:00-04:00",
    aiSummary: {
      whyAttend: "Learn cutting-edge teaching strategies with hands-on practice sessions.",
      whosThere: "K-12 teachers from Washtenaw County, U of M education faculty, and ed-tech startups.",
      vibe: "Collaborative workshop atmosphere. Coffee and materials provided.",
    },
    source: "ibm_rpa",
    matchScore: 70,
    rsvpCount: 65,
    createdAt: "2026-05-06T08:00:00Z",
  },
  {
    id: "evt-006",
    title: "Michigan Skilled Trades Hiring Event",
    description:
      "Electricians, plumbers, HVAC techs, and welders — Michigan contractors are hiring. Walk-in interviews, apprenticeship info, and certification guidance.",
    location: "Macomb Community College, Warren, MI",
    locationType: "detroit-metro",
    eventType: "career-fair",
    industry: "Trades",
    eventDate: "2026-07-10T10:00:00-04:00",
    aiSummary: {
      whyAttend: "Walk-in interviews with Michigan's top contractors. Apprenticeship pathways available for career changers.",
      whosThere: "Union reps, general contractors, and skilled trades employers from Southeast Michigan.",
      vibe: "Casual and practical. Bring your certifications. Lunch provided.",
    },
    source: "user_submitted",
    matchScore: 65,
    rsvpCount: 140,
    createdAt: "2026-05-15T14:00:00Z",
  },
  {
    id: "evt-007",
    title: "Detroit FinTech & Banking Mixer",
    description:
      "Network with professionals from Ally Financial, Rocket Companies, and Flagstar Bank. Discuss digital banking, compliance, and fintech innovation in Michigan.",
    location: "The Apparatus Room, Detroit Foundation Hotel, Detroit, MI",
    locationType: "detroit-metro",
    eventType: "networking",
    industry: "Finance",
    eventDate: "2026-06-25T17:30:00-04:00",
    aiSummary: {
      whyAttend: "Connect with decision-makers from Michigan's growing fintech corridor.",
      whosThere: "Finance professionals, compliance officers, and software engineers from Detroit's banking sector.",
      vibe: "Upscale networking with cocktails and appetizers. Business casual.",
    },
    source: "api",
    matchScore: 78,
    rsvpCount: 55,
    createdAt: "2026-05-16T08:00:00Z",
  },
];
