import { Job } from "@/types/job";

export const mockJobs: Job[] = [
  {
    id: "job-001",
    title: "Cybersecurity Engineer",
    company: "DTE Energy",
    companyLogo: undefined,
    location: "Detroit, MI (Hybrid)",
    locationFilter: "detroit-metro",
    industry: "Technology",
    salaryRange: "$110K – $145K",
    description:
      "Protect DTE Energy's critical infrastructure by designing and implementing cybersecurity solutions across IT and OT environments. Work on threat detection, incident response, and security architecture for systems powering millions of Michigan residents. Collaborate with cross-functional teams to secure SCADA/ICS systems and enterprise cloud platforms.",
    requirements: [
      "Cybersecurity",
      "SIEM/SOAR",
      "Cloud Security (AWS/Azure)",
      "Network Security",
      "Python/Bash",
      "ICS/SCADA",
    ],
    matchScore: 75,
    matchReasons: [
      "Your Python scripting skills are directly applicable to DTE's security automation needs.",
      "Cloud familiarity provides a foundation for their hybrid cloud security environment.",
    ],
    skillGaps: [
      "SIEM/SOAR platform experience (Splunk, Sentinel) — core to their SOC operations.",
      "ICS/SCADA security knowledge — essential for protecting critical energy infrastructure.",
    ],
    referralAvailable: true,
    referralContactName: "David L.",
    referralContactId: "usr-insider-001",
    sourceUrl: "https://careers.dteenergy.com",
    postedAt: "2026-05-12T00:00:00Z",
    createdAt: "2026-05-12T00:00:00Z",
  },
  {
    id: "job-002",
    title: "Software Engineer — Cloud & Data",
    company: "DTE Energy",
    companyLogo: undefined,
    location: "Detroit, MI",
    locationFilter: "detroit-metro",
    industry: "Technology",
    salaryRange: "$105K – $135K",
    description:
      "Design and develop cloud-native applications and data pipelines that power DTE Energy's digital transformation and grid modernization initiatives. Work with AWS services, Databricks, and enterprise platforms (SAP, ServiceNow) to build scalable solutions supporting Michigan's energy future.",
    requirements: [
      "Python",
      "AWS",
      "SQL",
      "Databricks/Spark",
      "REST APIs",
      "Agile/Scrum",
    ],
    matchScore: 88,
    matchReasons: [
      "Your Python and SQL skills are core requirements for DTE's cloud engineering team.",
      "REST API experience aligns with their enterprise integration needs.",
      "Agile methodology matches their project delivery approach.",
    ],
    skillGaps: [
      "Databricks/Spark experience — central to their data engineering platform.",
    ],
    referralAvailable: false,
    sourceUrl: "https://careers.dteenergy.com",
    postedAt: "2026-05-14T00:00:00Z",
    createdAt: "2026-05-14T00:00:00Z",
  },
  {
    id: "job-003",
    title: "Data & AI Sales Engineer",
    company: "IBM",
    companyLogo: undefined,
    location: "Detroit, MI (Ally Detroit Center, 500 Woodward Ave)",
    locationFilter: "detroit-metro",
    industry: "Technology",
    salaryRange: "$120K – $160K",
    description:
      "Join IBM's Detroit office as a Data & AI Sales Engineer, helping enterprise clients across Michigan adopt watsonx, hybrid cloud, and AI solutions. Conduct technical demonstrations, build proof-of-concepts, and translate complex AI capabilities into business value for automotive, financial services, and energy sector clients.",
    requirements: [
      "AI/ML Concepts",
      "Python",
      "Cloud Platforms (IBM Cloud/AWS)",
      "Data Architecture",
      "Client-facing Communication",
      "Solution Architecture",
    ],
    matchScore: 85,
    matchReasons: [
      "Your Python and machine learning background directly aligns with IBM's watsonx technical sales needs.",
      "Strong communication skills complement the client-facing nature of this role.",
    ],
    skillGaps: [
      "IBM Cloud and watsonx platform experience — foundational to this role.",
      "Enterprise sales engineering experience — technical demos and client presentations.",
    ],
    referralAvailable: true,
    referralContactName: "Priya M.",
    referralContactId: "usr-insider-003",
    sourceUrl: "https://ibm.com/careers",
    postedAt: "2026-05-10T00:00:00Z",
    createdAt: "2026-05-10T00:00:00Z",
  },
  {
    id: "job-004",
    title: "System Services Representative",
    company: "IBM",
    companyLogo: undefined,
    location: "Detroit, MI",
    locationFilter: "detroit-metro",
    industry: "Technology",
    salaryRange: "$85K – $110K",
    description:
      "Install, maintain, and repair IBM hardware and software systems across enterprise client sites in Southeast Michigan. Work with IBM Power systems, multi-vendor environments, and provide technical support for critical infrastructure. Opportunities to grow into cloud and AI infrastructure specializations.",
    requirements: [
      "Hardware/Software Troubleshooting",
      "Linux/AIX",
      "Networking Fundamentals",
      "IBM Power Systems",
      "Customer Service",
      "Problem Solving",
    ],
    matchScore: 62,
    matchReasons: [
      "Problem-solving skills and technical aptitude match the troubleshooting demands of this role.",
    ],
    skillGaps: [
      "IBM Power systems administration — core hardware expertise required.",
      "Linux/AIX system administration — essential for infrastructure work.",
      "On-site hardware installation and maintenance experience.",
    ],
    referralAvailable: false,
    sourceUrl: "https://ibm.com/careers",
    postedAt: "2026-05-08T00:00:00Z",
    createdAt: "2026-05-08T00:00:00Z",
  },
  {
    id: "job-005",
    title: "Senior Software Engineer — Active Safety",
    company: "Robert Bosch LLC",
    companyLogo: undefined,
    location: "Plymouth, MI",
    locationFilter: "detroit-metro",
    industry: "Automotive",
    salaryRange: "$125K – $165K",
    description:
      "Develop embedded software for Bosch's next-generation active safety systems including brake modulators and electronic brake boosters at the Plymouth technical center. Work with AUTOSAR architecture, functional safety standards (ISO 26262), and ASPICE processes to deliver software that saves lives in millions of vehicles worldwide.",
    requirements: [
      "Embedded C/C++",
      "AUTOSAR",
      "MATLAB/Simulink",
      "ISO 26262",
      "Git/CI-CD",
      "ASPICE",
    ],
    matchScore: 68,
    matchReasons: [
      "Software engineering fundamentals and Git workflow experience provide a foundation.",
      "Analytical mindset aligns with safety-critical embedded systems development.",
    ],
    skillGaps: [
      "Embedded C/C++ — the primary development language for automotive ECUs.",
      "AUTOSAR architecture knowledge — industry-standard for automotive software.",
      "MATLAB/Simulink — used extensively for model-based development.",
    ],
    referralAvailable: false,
    sourceUrl: "https://bosch.us/careers",
    postedAt: "2026-05-11T00:00:00Z",
    createdAt: "2026-05-11T00:00:00Z",
  },
  {
    id: "job-006",
    title: "Software Engineer — Enterprise Systems",
    company: "Rivian",
    companyLogo: undefined,
    location: "Plymouth, MI",
    locationFilter: "detroit-metro",
    industry: "Technology",
    salaryRange: "$115K – $150K",
    description:
      "Build and scale enterprise software systems powering Rivian's supply chain, manufacturing operations, and internal tools at their Plymouth, MI engineering hub. Work across the full stack with modern frameworks to support the production of Rivian's electric vehicles and grow within one of Michigan's most exciting EV companies.",
    requirements: [
      "TypeScript/JavaScript",
      "React",
      "Node.js",
      "PostgreSQL",
      "REST/GraphQL APIs",
      "AWS",
    ],
    matchScore: 92,
    matchReasons: [
      "Your React, TypeScript, and Node.js skills are a strong match for Rivian's enterprise software stack.",
      "REST API and database experience directly aligns with their backend requirements.",
      "Full-stack capability fits their small, high-impact team structure.",
    ],
    skillGaps: [
      "GraphQL — used alongside REST in their API layer.",
    ],
    referralAvailable: true,
    referralContactName: "Alex K.",
    referralContactId: "usr-insider-004",
    sourceUrl: "https://careers.rivian.com",
    postedAt: "2026-05-13T00:00:00Z",
    createdAt: "2026-05-13T00:00:00Z",
  },
  {
    id: "job-007",
    title: "Principal Software Engineer — Autonomous Driving",
    company: "Magna International",
    companyLogo: undefined,
    location: "Troy, MI",
    locationFilter: "detroit-metro",
    industry: "Automotive",
    salaryRange: "$140K – $180K",
    description:
      "Lead the development of autonomous driving software at Magna's Troy technical center. Work on image signal processing, sensor fusion, and perception algorithms for next-generation ADAS and self-driving platforms. Collaborate with global engineering teams to deliver production-ready autonomous driving features for major automotive OEMs.",
    requirements: [
      "C++",
      "Python",
      "Computer Vision",
      "Deep Learning (PyTorch/TensorFlow)",
      "ROS",
      "Linux",
    ],
    matchScore: 80,
    matchReasons: [
      "Strong Python foundation matches their prototyping and ML pipeline requirements.",
      "Machine learning interest aligns with their perception and sensor fusion team.",
    ],
    skillGaps: [
      "C++ proficiency — core for performance-critical autonomous driving systems.",
      "Computer Vision specialization (OpenCV, point cloud processing).",
      "ROS (Robot Operating System) — used for sensor integration.",
    ],
    referralAvailable: false,
    sourceUrl: "https://magna.com/careers",
    postedAt: "2026-05-09T00:00:00Z",
    createdAt: "2026-05-09T00:00:00Z",
  },
  {
    id: "job-008",
    title: "Data Engineer",
    company: "Rocket Companies",
    companyLogo: undefined,
    location: "Detroit, MI",
    locationFilter: "detroit-metro",
    industry: "Finance",
    salaryRange: "$110K – $140K",
    description:
      "Design and build data pipelines that power Rocket Mortgage's AI-driven lending decisions. Work with massive datasets, real-time streaming architectures, and help make homeownership more accessible.",
    requirements: ["SQL", "Python", "Spark/Databricks", "Airflow", "AWS", "Data Modeling"],
    matchScore: 92,
    matchReasons: [
      "Your SQL and Python skills are core requirements for this role.",
      "Experience with data analysis aligns with their pipeline engineering needs.",
    ],
    skillGaps: [
      "Apache Spark — consider hands-on practice with Databricks Community Edition.",
      "Airflow orchestration experience would strengthen your application.",
    ],
    referralAvailable: true,
    referralContactName: "Marcus T.",
    referralContactId: "usr-insider-005",
    sourceUrl: "https://rocketcompanies.com/careers",
    postedAt: "2026-05-14T00:00:00Z",
    createdAt: "2026-05-14T00:00:00Z",
  },
];
